name: photokredy_core
description: Core project for PhotoKredy
version: 0.0.1
author: Herizo Ramaroson
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  plugin:
    androidPackage: com.hramaroson.photokredy.core
    pluginClass: PhotokredyCorePlugin