name: photokredy_core_sample
description: Sample app for testing puspose
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2  

dev_dependencies:
  flutter_test: 
    sdk: flutter
    
  photokredy_core:
    path: ../

flutter:
  uses-material-design: true 