coverage:
  precision: 1
  round: down
  range: "30...70"

  status:
    project:
      default:
        target: 40%
    patch:
      default:
        target: 70%
    changes: no

comment:
  # diff, changes, footer, reach, flags, suggestions
  layout: "header, files"
